export type Product = {
  id: string;
  title: string;
  brandName: string;
  brandLogo: string;
  originalPrice: number;
  salePrice: number;
  rating: number;
  reviewsCount: number;
  soldCount: number;
  imageUrl: string;
  category: string;
  description?: string;
  features?: string[];
  additionalImages?: string[];
  flipkartUrl?: string;
};

export const categories = [
  "Electronics",
  "Home Decor",
  "Home & Kitchen",
  "Accessories",
  "Clothes",
  "Bags",
  "Food",
  "Furniture",
  "Baby Care",
  "Beauty & Makeup",
  "Stationery",
  "Grocery",
  "Books",
];

const rawProducts: Product[] = [
  {
    id: "1",
    title: "Sapra Chopper to Chop and Cut Fruits, Vegetables(PACK OF 1) Vegetable & Fruit Chopper",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 0,
    originalPrice: 999,
    salePrice: 237,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/chopper/b/u/2/plastic-alloy-steel-quick-and-powerful-manual-hand-press-large-original-imaghq6hpfhz7xhz.jpeg?q=70",
    category: "Home & Kitchen",
    description: "Sapra Chopper to Chop and Cut Fruits, Vegetables(PACK OF 1) Vegetable & Fruit Chopper - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/sapra-chopper-chop-cut-fruits-vegetables-pack-1-vegetable-fruit/p/itm2c634c05a1caf?pid=CPRGHP3AZEADX5YS"
  },
  {
    id: "2",
    title: "DS99 KT-125 Dynamic Thunder Sound With High Bass & Mobile Stand 10 W Bluetooth Speaker",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 1,
    originalPrice: 2699,
    salePrice: 389,
    rating: 2.3,
    reviewsCount: 3,
    soldCount: 4,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/speaker/mobile-tablet-speaker/g/l/u/kt-125-dynamic-thunder-sound-with-high-bass-mobile-stand-ds99-original-imagayh9qzyac8rz.jpeg?q=70",
    category: "Electronics",
    description: "DS99 KT-125 Dynamic Thunder Sound With High Bass & Mobile Stand 10 W Bluetooth Speaker - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/ds99-kt-125-dynamic-thunder-sound-high-bass-mobile-stand-10-w-bluetooth-speaker/p/itm1ef55b7259ddf?pid=ACCGH9YRAA5H4ZBD"
  },
  {
    id: "3",
    title: "DS99 High Power Sound Blast, Mini, Thunder Sound Wireless Bluetoo...more",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 2,
    originalPrice: 1999,
    salePrice: 297,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://picsum.photos/400/300",
    category: "Electronics",
    description: "DS99 High Power Sound Blast, Mini, Thunder Sound Wireless Bluetoo...more - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/ds99-high-power-sound-blast-mini-thunder-wireless-bluetooth-speaker-3-w/p/itm24f186769c19a?pid=ACCGZXW5BHK77YZV"
  },
  {
    id: "4",
    title: "ZEBRONICS 4 Port ZEB-90HB USB Hub",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 3,
    originalPrice: 1999,
    salePrice: 198,
    rating: 3.7,
    reviewsCount: 10241,
    soldCount: 15361,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/ksgehzk0/usb-gadget/q/c/q/usb-hub-zeb-90hb-zebronics-original-imag6ymzfeyuevmt.jpeg?q=70",
    category: "Electronics",
    description: "ZEBRONICS 4 Port ZEB-90HB USB Hub - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/zebronics-4-port-zeb-90hb-usb-hub/p/itm040238e390e8d?pid=USGG4Z3KEWHYW2MG"
  },
  {
    id: "5",
    title: "sdt Decorative Showpiece  -  13 cm",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 4,
    originalPrice: 1099,
    salePrice: 132,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/showpiece-figurine/f/0/k/11-11-porcelain-adiyogi-shiva-lord-shankar-idol-black-sdt-13-original-imagg5qyh6umhrhh.jpeg?q=70",
    category: "Home Decor",
    description: "sdt Decorative Showpiece  -  13 cm - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/sdt-decorative-showpiece-13-cm/p/itm1417305b6c610?pid=SHIGG5QZRNCZJSNZ"
  },
  {
    id: "6",
    title: "SPKR Couple Legs hanging statue gift for Girlfriend /boyfriend Decorative Showpiece  -  5 cm",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 5,
    originalPrice: 2499,
    salePrice: 539,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/showpiece-figurine/h/7/g/7-19-showpiece-spkr-5-original-imagg94cktpra7gp.jpeg?q=70",
    category: "Home Decor",
    description: "SPKR Couple Legs hanging statue gift for Girlfriend /boyfriend Decorative Showpiece  -  5 cm - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/spkr-couple-legs-hanging-statue-gift-girlfriend-boyfriend-decorative-showpiece-5-cm/p/itm7681bf4344bda?pid=SHIGG94CV9KB6YTZ"
  },
  {
    id: "7",
    title: "Shilp Saga Lord Ganesha Idol on Decorative Handcrafted Plate for Home and Car Decorative Decorative Showpiece  -  20 cm",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 6,
    originalPrice: 1999,
    salePrice: 235,
    rating: 4.2,
    reviewsCount: 573,
    soldCount: 859,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/showpiece-figurine/w/k/a/6-14-sd45-shilp-saga-20-original-imahc55rqrg9taqx.jpeg?q=70",
    category: "Home Decor",
    description: "Shilp Saga Lord Ganesha Idol on Decorative Handcrafted Plate for Home and Car Decorative Decorative Showpiece  -  20 cm - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/shilp-saga-lord-ganesha-idol-decorative-handcrafted-plate-home-car-showpiece-20-cm/p/itm4b55fa07fdee4?pid=SHIG4U44XUFTPWAD"
  },
  {
    id: "8",
    title: "SPKR Ganesha Idol, Vinayaka Statue, Ganpati Decorative Statue Decorative Showpiece  -  3 cm",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 7,
    originalPrice: 999,
    salePrice: 175,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/showpiece-figurine/5/u/2/5-7-mu0001-spkr-3-original-imagg8sdqgq4xgzx.jpeg?q=70",
    category: "Home Decor",
    description: "SPKR Ganesha Idol, Vinayaka Statue, Ganpati Decorative Statue Decorative Showpiece  -  3 cm - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/spkr-ganesha-idol-vinayaka-statue-ganpati-decorative-statue-showpiece-3-cm/p/itm01fb4c0e006c6?pid=SHIGG8SDQAPQGYSP"
  },
  {
    id: "9",
    title: "SDR Front & Back Case for Airpods 1/2 Dots Protective Cover AirPods 1/2 Earphone Cases",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 8,
    originalPrice: 999,
    salePrice: 353,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/cases-covers/front-back-case/h/b/i/back-cover-for-airpods-dots-protective-cover-airpods-earphone-original-imagjcry6hfgpyu2.jpeg?q=70",
    category: "Accessories",
    description: "SDR Front & Back Case for Airpods 1/2 Dots Protective Cover AirPods 1/2 Earphone Cases - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/sdr-front-back-case-airpods-1-2-dots-protective-cover-earphone-cases/p/itmcf0a5d3a757eb?pid=ACCGJCRYNJZPYGZG"
  },
  {
    id: "10",
    title: "Sapra LCD Writing Screen Tablet Drawing Board for Kids/Adults, 8.5 Inch",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 9,
    originalPrice: 4800,
    salePrice: 150,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/learning-toy/p/y/e/lcd-writing-screen-tablet-drawing-board-for-kids-adults-8-5-inch-original-imagztqfd3whhekh.jpeg?q=70",
    category: "Electronics",
    description: "Sapra LCD Writing Screen Tablet Drawing Board for Kids/Adults, 8.5 Inch - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/sapra-lcd-writing-screen-tablet-drawing-board-kids-adults-8-5-inch/p/itma07255fa84e58?pid=ETYGZTQFFNVYERGR"
  },
  {
    id: "11",
    title: "Tejash enterprises Dream Catcher Wall Hanging bluee 25 cm Feather Dream Catcher",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 10,
    originalPrice: 825,
    salePrice: 140,
    rating: 3.8,
    reviewsCount: 28,
    soldCount: 42,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/kolsscw0/wind-chime/l/u/x/mini-blue-goldy-traders-original-imag3yzmqzwqhgg5.jpeg?q=70",
    category: "Home Decor",
    description: "Tejash enterprises Dream Catcher Wall Hanging bluee 25 cm Feather Dream Catcher - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/tejash-enterprises-dream-catcher-wall-hanging-bluee-25-cm-feather/p/itm16b0f9a556009?pid=WCHFYCEPSUWDB2ER"
  },
  {
    id: "12",
    title: "Sapra Lord Buddha Statue Sculpture Home Decor Decorative Showpiece  -  29 cm",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 11,
    originalPrice: 1999,
    salePrice: 425,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/showpiece-figurine/6/s/q/2-11-sdr001-sapra-29-original-imagh2yppjsf5hgf.jpeg?q=70",
    category: "Home Decor",
    description: "Sapra Lord Buddha Statue Sculpture Home Decor Decorative Showpiece  -  29 cm - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/sapra-lord-buddha-statue-sculpture-home-decor-decorative-showpiece-29-cm/p/itmcaa0c7ca50e15?pid=SHIGH2YPGEFGKRJG"
  },
  {
    id: "13",
    title: "ZEBRONICS USB Type C Cable 2 A 1 m ZEB-TT20V",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 12,
    originalPrice: 999,
    salePrice: 249,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/data-cable/usb-type-c-cable/b/u/d/zeb-tt20v-zebronics-original-imagg6vxgycbyqja.jpeg?q=70",
    category: "Electronics",
    description: "ZEBRONICS USB Type C Cable 2 A 1 m ZEB-TT20V - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/zebronics-usb-type-c-cable-2-1-m-zeb-tt20v/p/itm26ad8d22e6f12?pid=ACCGG6VXNUFYTUME"
  },
  {
    id: "14",
    title: "DS99 TG 113 5 W Bluetooth Speaker",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 13,
    originalPrice: 2399,
    salePrice: 360,
    rating: 3.7,
    reviewsCount: 6,
    soldCount: 9,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/speaker/mobile-tablet-speaker/x/7/o/tg113-ds99-original-imahfzg2hngqyffg.jpeg?q=70",
    category: "Electronics",
    description: "DS99 TG 113 5 W Bluetooth Speaker - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/ds99-tg-113-5-w-bluetooth-speaker/p/itm558c7625fb5c3?pid=ACCGH5YUGY2JM42X"
  },
  {
    id: "15",
    title: "curious lifestyle Meditating Sitting Buddha Statue showpiece Idol Home Decor Items for Living Room Decorative Showpiece  -  25.4 cm",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 14,
    originalPrice: 1299,
    salePrice: 144,
    rating: 4,
    reviewsCount: 11914,
    soldCount: 17871,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/showpiece-figurine/p/y/e/10-17-78-buddha-home-deocr-s-curious-lifestyle-25-4-original-imahkrcbjgktfmvb.jpeg?q=70",
    category: "Home Decor",
    description: "curious lifestyle Meditating Sitting Buddha Statue showpiece Idol Home Decor Items for Living Room Decorative Showpiece  -  25.4 cm - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/curious-lifestyle-meditating-sitting-buddha-statue-showpiece-idol-home-decor-items-living-room-decorative-25-4-cm/p/itm7874f687e4117?pid=SHIFPPS34GZDH6R9"
  },
  {
    id: "16",
    title: "Sapra Lord Ganesha Decorated by Stone with Wooden Base Decorative with Tree Showpiece Decorative Showpiece  -  13.5 cm",
    brandName: "Flipkart Seller",
    brandLogo: "https://i.pravatar.cc/150?u=" + 15,
    originalPrice: 999,
    salePrice: 261,
    rating: 0,
    reviewsCount: 0,
    soldCount: 0,
    imageUrl: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/showpiece-figurine/z/5/h/8-7-tg-001-sapra-13-5-original-imah9rv2udhhh3h5.jpeg?q=70",
    category: "Home Decor",
    description: "Sapra Lord Ganesha Decorated by Stone with Wooden Base Decorative with Tree Showpiece Decorative Showpiece  -  13.5 cm - Buy online at best prices.",
    features: ["High Quality", "Durable", "Best in class"],
    additionalImages: [],
    flipkartUrl: "https://www.flipkart.com/sapra-lord-ganesha-decorated-stone-wooden-base-decorative-tree-showpiece-13-5-cm/p/itm3377f06b3cb15?pid=SHIGH6V3PGEEZE5W"
  }
];

export const products = rawProducts.map(p => ({
  ...p,
  rating: p.soldCount === 0 ? 5 : p.rating
}));

export const testimonials = [
  {
    id: "t1",
    name: "Aarav Mehta",
    rating: 5,
    quote: "Bought the Adiyogi statue and a Buddha showpiece for my living room. The detail is stunning and it arrived safely packaged!",
    brandRef: "Home Decor",
  },
  {
    id: "t2",
    name: "Priya Sharma",
    avatar: "https://i.pravatar.cc/150?u=priya",
    rating: 5,
    quote: "The manual hand press chopper is a lifesaver in the kitchen. Very sharp blades and sturdy build. Delivery was super quick!",
    brandRef: "Kitchen Essentials",
  },
  {
    id: "t3",
    name: "Rohan Das",
    rating: 5,
    quote: "Ordered the Zebronics USB hub and Type-C cables. Excellent build quality, works perfectly with my laptop, and prices are unbeatable.",
    brandRef: "Tech & Accessories",
  },
  {
    id: "t4",
    name: "Ananya Iyer",
    avatar: "https://i.pravatar.cc/150?u=ananya",
    rating: 4,
    quote: "Love the DS99 Bluetooth speaker! The bass is amazing for its size, and the mobile stand is very convenient.",
    brandRef: "Audio Gear",
  },
];

